#!/usr/bin/env node
/**
 * GRAG Production ERP - one-shot setup.
 *
 *   npm run setup
 *
 * Walks through everything needed to run the app:
 *   1. hosting port
 *   2. PostgreSQL connection (expects an existing server on port 6789)
 *   3. creates the database if it is missing
 *   4. generates SESSION_SECRET and JWT_SECRET
 *   5. collects the Google OAuth client id / secret and Drive folder
 *   6. writes server/.env
 *   7. runs the migrations
 *   8. seeds the single root user
 *
 * Re-running is safe: existing answers are offered as defaults and no data is
 * dropped.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import readline from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const here = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(here, '..');
const serverDir = path.join(rootDir, 'server');
const envPath = path.join(serverDir, '.env');

const rl = readline.createInterface({ input, output });

// Reading through the async iterator keeps lines buffered, so the script works
// both interactively and when answers are piped in (printf ... | npm run setup).
const lines = rl[Symbol.asyncIterator]();
let stdinExhausted = false;

function heading(text) {
  console.log(`\n\x1b[1m${text}\x1b[0m`);
}

async function ask(label, fallback = '') {
  const suffix = fallback ? ` [${fallback}]` : '';
  output.write(`  ${label}${suffix}: `);

  if (stdinExhausted) {
    output.write(`${fallback}\n`);
    return fallback;
  }

  const { value, done } = await lines.next();
  if (done) {
    // No more input: accept the defaults for everything that follows.
    stdinExhausted = true;
    output.write(`${fallback}\n`);
    return fallback;
  }

  const answer = String(value).trim();
  if (!answer) output.write('\n');
  return answer || fallback;
}

async function askRequired(label, fallback = '') {
  for (;;) {
    const answer = await ask(label, fallback);
    if (answer) return answer;
    if (stdinExhausted) throw new Error(`"${label}" is required and no value was supplied.`);
    console.log('    this one is required');
  }
}

async function askUntil(label, fallback, validate, hint) {
  for (;;) {
    const answer = await ask(label, fallback);
    if (validate(answer)) return answer;
    if (stdinExhausted) throw new Error(`"${label}" is invalid (${hint}) and cannot be prompted.`);
    console.log(`    ${hint}`);
  }
}

/** Parse an existing .env into a plain object so re-runs keep prior answers. */
async function readExistingEnv() {
  try {
    const text = await fs.readFile(envPath, 'utf8');
    const values = {};
    for (const line of text.split('\n')) {
      const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
      if (match) values[match[1]] = match[2];
    }
    return values;
  } catch {
    return {};
  }
}

function renderEnv(values) {
  return `# Generated by "npm run setup" on ${new Date().toISOString()}
# Safe to edit by hand; re-running setup keeps these as defaults.

PORT=${values.PORT}
NODE_ENV=${values.NODE_ENV}
APP_URL=${values.APP_URL}

PGHOST=${values.PGHOST}
PGPORT=${values.PGPORT}
PGDATABASE=${values.PGDATABASE}
PGUSER=${values.PGUSER}
PGPASSWORD=${values.PGPASSWORD}

SESSION_SECRET=${values.SESSION_SECRET}
JWT_SECRET=${values.JWT_SECRET}
IDLE_TIMEOUT_MINUTES=${values.IDLE_TIMEOUT_MINUTES}

GOOGLE_CLIENT_ID=${values.GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${values.GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${values.GOOGLE_REDIRECT_URI}
GOOGLE_DRIVE_FOLDER_ID=${values.GOOGLE_DRIVE_FOLDER_ID}

ROOT_EMAIL=${values.ROOT_EMAIL}
ROOT_NAME=${values.ROOT_NAME}
ROOT_USERNAME=${values.ROOT_USERNAME}
ROOT_PIN=${values.ROOT_PIN}
`;
}

/** Connect to the maintenance database and create ours if it does not exist. */
async function ensureDatabase(values) {
  const admin = new pg.Client({
    host: values.PGHOST,
    port: Number(values.PGPORT),
    user: values.PGUSER,
    password: values.PGPASSWORD,
    database: 'postgres',
  });

  await admin.connect();
  try {
    const { rowCount } = await admin.query('SELECT 1 FROM pg_database WHERE datname = $1', [
      values.PGDATABASE,
    ]);
    if (rowCount === 0) {
      // Identifiers cannot be parameterised; the name is validated before this point.
      await admin.query(`CREATE DATABASE "${values.PGDATABASE}"`);
      console.log(`  created database "${values.PGDATABASE}"`);
    } else {
      console.log(`  database "${values.PGDATABASE}" already exists`);
    }
  } finally {
    await admin.end();
  }
}

async function main() {
  console.log('\n\x1b[1mGRAG Production ERP - setup\x1b[0m');
  console.log('  Press Enter to accept the value in brackets.');

  const prev = await readExistingEnv();
  const values = {};

  heading('1. Hosting');
  values.PORT = await ask('HTTP port', prev.PORT || '5000');
  values.APP_URL = await ask('Public app URL', prev.APP_URL || `http://localhost:${values.PORT}`);
  values.NODE_ENV = prev.NODE_ENV || 'development';
  values.IDLE_TIMEOUT_MINUTES = await ask(
    'Idle logout (minutes)',
    prev.IDLE_TIMEOUT_MINUTES || '10',
  );

  heading('2. PostgreSQL');
  console.log('  Expects a PostgreSQL server that is already running.');
  values.PGHOST = await ask('Host', prev.PGHOST || 'localhost');
  values.PGPORT = await ask('Port', prev.PGPORT || '6789');
  values.PGUSER = await ask('User', prev.PGUSER || 'postgres');
  values.PGPASSWORD = await ask('Password', prev.PGPASSWORD || '');
  values.PGDATABASE = await askUntil(
    'Database name',
    prev.PGDATABASE || 'grag_erp',
    (name) => /^[a-z_][a-z0-9_]*$/i.test(name),
    'use letters, digits and underscores only',
  );

  heading('3. Creating the database');
  try {
    await ensureDatabase(values);
  } catch (error) {
    console.error(`\n  Could not reach PostgreSQL at ${values.PGHOST}:${values.PGPORT}`);
    console.error(`  ${error.message}`);
    console.error('  Start the server (or correct the details) and run setup again.\n');
    rl.close();
    process.exit(1);
  }

  heading('4. Secrets');
  values.SESSION_SECRET = prev.SESSION_SECRET || crypto.randomBytes(32).toString('hex');
  values.JWT_SECRET = prev.JWT_SECRET || crypto.randomBytes(32).toString('hex');
  console.log(`  SESSION_SECRET ${prev.SESSION_SECRET ? 'kept' : 'generated'}`);
  console.log(`  JWT_SECRET     ${prev.JWT_SECRET ? 'kept' : 'generated'}`);

  heading('5. Google sign-in');
  console.log('  Google Cloud Console > APIs & Services > Credentials > OAuth client ID (Web).');
  console.log('  Add this under "Authorised redirect URIs", character for character:');
  console.log(`      ${values.APP_URL}/api/auth/google/callback`);
  console.log('  Enable the Google Drive API too if you want the Backup button to work.');
  values.GOOGLE_CLIENT_ID = await ask('Client ID', prev.GOOGLE_CLIENT_ID || '');
  values.GOOGLE_CLIENT_SECRET = await ask('Client secret', prev.GOOGLE_CLIENT_SECRET || '');
  values.GOOGLE_REDIRECT_URI = await ask(
    'Redirect URI (must match the Console entry exactly)',
    prev.GOOGLE_REDIRECT_URI || `${values.APP_URL}/api/auth/google/callback`,
  );

  // Google answers a non-loopback http:// redirect with a bare
  // "Error 400: invalid_request", so it is worth catching here instead.
  const { redirectUriProblem } = await import('../server/src/config/google.js');
  const uriProblem = redirectUriProblem(values.GOOGLE_REDIRECT_URI);
  if (uriProblem) {
    console.log(`\n  Warning: ${uriProblem}\n`);
  }
  values.GOOGLE_DRIVE_FOLDER_ID = await ask(
    'Drive folder id for backups (blank = My Drive root)',
    prev.GOOGLE_DRIVE_FOLDER_ID || '',
  );
  if (!values.GOOGLE_CLIENT_ID || !values.GOOGLE_CLIENT_SECRET) {
    console.log('  Left blank - sign-in stays disabled until you fill these into server/.env.');
  }

  heading('6. Root user');
  console.log('  The one account that can assign every other role.');
  values.ROOT_EMAIL = await askUntil(
    'Google account email',
    prev.ROOT_EMAIL || '',
    (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value),
    'enter a valid email address',
  );
  values.ROOT_NAME = await askRequired('Display name', prev.ROOT_NAME || 'Root');
  values.ROOT_USERNAME = await askUntil(
    'Username (max 12 chars)',
    prev.ROOT_USERNAME || 'root',
    (value) => value.length > 0 && value.length <= 12,
    'between 1 and 12 characters',
  );
  values.ROOT_PIN = await askUntil(
    '4-digit PIN',
    prev.ROOT_PIN || '',
    (value) => /^\d{4}$/.test(value),
    'exactly 4 digits',
  );

  heading('7. Writing server/.env');
  await fs.writeFile(envPath, renderEnv(values), 'utf8');
  console.log(`  wrote ${path.relative(rootDir, envPath)}`);

  // Load the freshly written env before importing modules that read it.
  for (const [key, value] of Object.entries(values)) process.env[key] = value;

  heading('8. Migrations');
  const { runMigrations } = await import('../server/src/db/migrate.js');
  await runMigrations({ log: console.log });

  heading('9. Root user');
  const { seedRoot } = await import('../server/src/db/seedRoot.js');
  const root = await seedRoot({
    email: values.ROOT_EMAIL,
    name: values.ROOT_NAME,
    username: values.ROOT_USERNAME,
    pin: values.ROOT_PIN,
  });
  console.log(`  root ready: ${root.email} (username "${root.username}")`);

  const { closePool } = await import('../server/src/config/db.js');
  await closePool();

  console.log('\n\x1b[1mSetup complete.\x1b[0m');
  console.log('  npm install     install dependencies (if you have not already)');
  console.log('  npm run dev     server on :' + values.PORT + ' + Vite client with hot reload');
  console.log('  npm run build && npm start    production build served from :' + values.PORT);
  console.log('');

  rl.close();
}

main().catch((error) => {
  console.error(`\nSetup failed: ${error.message}\n`);
  rl.close();
  process.exit(1);
});
